"""Pydantic schema for project configuration."""

from pathlib import Path

from pydantic import BaseModel, Field


class ProjectConfig(BaseModel):
    """User choices that define what is generated by init."""

    framework: str = Field(..., description="Agent framework")
    project_type: str = Field(..., description="Project type")
    pipeline: str = Field(..., description="CI/CD pipeline")
    runtime: str = Field(..., description="Runtime environment")
    iac: str = Field(..., description="Infrastructure as Code")
    target_dir: Path = Field(default=Path("."), description="Target directory")
    template_version: str | None = Field(default=None, description="Template version (semver or tag)")
    overwrite: bool = Field(default=False, description="Allow init in non-empty directory")
    non_interactive: bool = Field(default=False, description="Fail if any option missing")

    model_config = {"frozen": True}


# Enums for validation (string values match CLI flags)
FRAMEWORKS = ("google_adk", "microsoft_agent_framework", "crewai", "langgraph")
PROJECT_TYPES = ("multi_agent_api", "multi_agent_react_ui", "agentic_rag")
PIPELINES = ("github_actions", "azure_devops")
RUNTIMES = ("aks", "container_apps", "app_service")
IAC_OPTIONS = ("terraform", "bicep")
